name = "UniqueIDs"
uuid = "20dae3cf-a72a-46c2-a81c-a5a401b1c55e"
authors = ["Nathan Zimmerberg <nzimmerberg@gmail.com>"]
version = "0.1.0"

[weakdeps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"

[extensions]
AxisKeysExt = "AxisKeys"

[compat]
AxisKeys = "0.2"
julia = "1.11"

[workspace]
projects = ["test"]
